version: '3.8'

services:
    db:
      container_name: pg_container
      image: postgres:13
      environment:
        - POSTGRES_USER=mao
        - POSTGRES_PASSWORD=123
        - POSTGRES_DB=cinema0
      ports:
        - 5432:5432


    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        environment:
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=root
        ports:
         - 5050:80